use std::num::NonZeroU32;

use documented::Documented;
use jsonrpsee::core::{JsonValue, RpcResult};
use schemars::JsonSchema;
use serde::Serialize;
use zcash_client_backend::data_api::{WalletRead, wallet::ConfirmationsPolicy};
use zcash_protocol::value::Zatoshis;

use crate::components::{
    database::DbConnection,
    json_rpc::{server::LegacyCode, utils::parse_account_parameter},
    keystore::KeyStore,
};

/// Response to a `z_getbalanceforaccount` RPC request.
pub(crate) type Response = RpcResult<ResultType>;
pub(crate) type ResultType = BalanceForAccount;

/// The spendable balance of an account, split by value pool.
#[derive(Clone, Debug, Serialize, Documented, JsonSchema)]
pub(crate) struct BalanceForAccount {
    /// The spendable balance held by the account in each value pool.
    ///
    /// Pools for which the balance is zero are omitted.
    pools: Pools,

    /// The `minconf` argument used to compute these balances.
    minimum_confirmations: u32,
}

#[derive(Clone, Debug, Serialize, JsonSchema)]
struct Pools {
    /// The amount held by the account in the transparent value pool.
    ///
    /// Omitted if zero.
    #[serde(skip_serializing_if = "Option::is_none")]
    transparent: Option<PoolBalance>,

    /// The amount held by the account in the Sapling value pool.
    ///
    /// Omitted if zero.
    #[serde(skip_serializing_if = "Option::is_none")]
    sapling: Option<PoolBalance>,

    /// The amount held by the account in the Orchard value pool.
    ///
    /// Omitted if zero.
    #[serde(skip_serializing_if = "Option::is_none")]
    orchard: Option<PoolBalance>,
}

#[derive(Clone, Debug, Serialize, JsonSchema)]
struct PoolBalance {
    /// The balance in zatoshis.
    #[serde(rename = "valueZat")]
    value_zat: u64,
}

pub(super) const PARAM_ACCOUNT_DESC: &str =
    "Either the UUID or ZIP 32 account index of the account.";
pub(super) const PARAM_MINCONF_DESC: &str =
    "Only include outputs in transactions confirmed at least this many times.";

pub(crate) async fn call(
    wallet: &DbConnection,
    keystore: &KeyStore,
    account: JsonValue,
    minconf: Option<u32>,
) -> Response {
    let account_id = parse_account_parameter(wallet, keystore, &account).await?;

    let confirmations_policy = match minconf {
        Some(minconf) => match NonZeroU32::new(minconf) {
            Some(c) => ConfirmationsPolicy::new_symmetrical(c, false),
            // `minconf = 0` currently cannot be represented accurately with
            // `ConfirmationsPolicy` (in particular it cannot represent zero-conf
            // fully-transparent spends), so for now we use "minimum possible".
            None => ConfirmationsPolicy::new_symmetrical(NonZeroU32::MIN, true),
        },
        None => ConfirmationsPolicy::new_symmetrical(NonZeroU32::MIN, false),
    };

    let summary = match wallet
        .get_wallet_summary(confirmations_policy)
        .map_err(|e| LegacyCode::Database.with_message(e.to_string()))?
    {
        Some(summary) => summary,
        None => return Err(LegacyCode::InWarmup.with_static("Wallet sync required")),
    };

    let account_balance = summary.account_balances().get(&account_id).ok_or_else(|| {
        LegacyCode::InvalidParameter.with_message(format!(
            "Error: account {account} has not been generated by z_getnewaccount."
        ))
    })?;

    Ok(BalanceForAccount {
        pools: Pools {
            transparent: pool_balance(account_balance.unshielded_balance().spendable_value()),
            sapling: pool_balance(account_balance.sapling_balance().spendable_value()),
            orchard: pool_balance(account_balance.orchard_balance().spendable_value()),
        },
        // `minconf` defaults to 1, matching zcashd.
        minimum_confirmations: minconf.unwrap_or(1),
    })
}

/// Renders a pool's spendable balance, omitting pools with a zero balance to
/// match the reference `z_getbalanceforaccount` behaviour.
fn pool_balance(value: Zatoshis) -> Option<PoolBalance> {
    (!value.is_zero()).then(|| PoolBalance {
        value_zat: value.into_u64(),
    })
}
