{
  # Reproducible aarch64 (arm64) build path for Zallet.
  #
  # The amd64 release artifact is built with StageX (full-source-bootstrapped,
  # bit-for-bit reproducible) via the repo Dockerfile. StageX cannot target
  # arm64 — its stage0 bootstrap seed is x86-only — so the arm64 artifact is
  # built here with Nix instead: pinned toolchain + pinned nixpkgs/crane =
  # rebuild-reproducible (verify with `diffoscope` across two clean builds).
  # This is a deliberate, documented asymmetry: amd64 is bootstrap-grade
  # reproducible; arm64 is rebuild-reproducible.
  #
  # Output: a STATIC aarch64-unknown-linux-musl `zallet` binary plus the
  # share-tree (completions, manpages, debian-copyright) laid out exactly like
  # the Dockerfile `export` stage, so the existing deb matrix + Release publish
  # consume it unchanged.
  description = "Zallet — reproducible static aarch64-musl build (arm64 release path)";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    crane.url = "github:ipetkov/crane/v0.20.3"; # pinned: master emits cargo --exclude-lockfile (cargo 1.86)
    rust-overlay = { url = "github:oxalica/rust-overlay"; inputs.nixpkgs.follows = "nixpkgs"; };
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, crane, rust-overlay, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; overlays = [ (import rust-overlay) ]; };

        muslTarget =
          if system == "aarch64-linux" then "aarch64-unknown-linux-musl"
          else "x86_64-unknown-linux-musl";

        # Match rust-toolchain.toml (1.85.1) + add the static-musl target.
        rustToolchain = pkgs.rust-bin.stable."1.85.1".default.override {
          targets = [ muslTarget ];
        };
        craneLib = (crane.mkLib pkgs).overrideToolchain rustToolchain;

        # cleanCargoSource strips non-Rust files, but zallet's build.rs needs the
        # Fluent (.ftl) i18n assets at compile time — keep those + i18n.toml.
        ftlOrCargo = path: type:
          (builtins.match ".*\\.ftl$" path != null)
          || (builtins.match ".*/i18n\\.toml$" path != null)
          || (craneLib.filterCargoSources path type);
        src = pkgs.lib.cleanSourceWith { src = ./.; filter = ftlOrCargo; name = "source"; };

        # StageX-style: compile the *-sys C deps with a MUSL-targeting clang. With
        # __clang__ defined, pqclean's compat.h skips the glibc-only <features.h>,
        # and the C objects link cleanly against musl (no __memcpy_chk/fcntl64).
        clang = pkgs.pkgsMusl.llvmPackages.clang;

        zallet = craneLib.buildPackage {
          inherit src;
          strictDeps = true;
          cargoExtraArgs = "--locked --bin zallet --features rpc-cli,zcashd-import";

          CARGO_BUILD_TARGET = muslTarget;
          CARGO_BUILD_RUSTFLAGS = "-C target-feature=+crt-static -C codegen-units=1";

          CC_aarch64_unknown_linux_musl = "${clang}/bin/clang";
          CXX_aarch64_unknown_linux_musl = "${clang}/bin/clang++";

          # protobuf for tonic (PROTOC); clang/libclang for bindgen; git because
          # zaino-state's build.rs shells out to git to embed the commit.
          nativeBuildInputs = with pkgs; [ protobuf llvmPackages.clang pkg-config git ];
          LIBCLANG_PATH = "${pkgs.llvmPackages.libclang.lib}/lib";
          PROTOC = "${pkgs.protobuf}/bin/protoc";

          doCheck = false;

          # Lay the artifact out like the Dockerfile `export` stage so the deb
          # matrix + Release publish need no structural change.
          postInstall = ''
            mkdir -p $out/share/zallet
            # completions + manpages are generated by zallet itself at build time;
            # the CI step regenerates them from the binary if absent here.
            if [ -d ${src}/zallet/contrib ]; then
              cp -r ${src}/zallet/contrib/* $out/share/zallet/ 2>/dev/null || true
            fi
          '';
        };
      in {
        packages.default = zallet;
        packages.zallet = zallet;
        # Convenience: the toolchain/deps closure the prebake CronJob seeds into
        # the S3 cache (so CI downloads instead of recompiling LLVM-musl).
        packages.deps = craneLib.buildDepsOnly {
          inherit src;
          cargoExtraArgs = "--locked --bin zallet --features rpc-cli,zcashd-import";
          CARGO_BUILD_TARGET = muslTarget;
          CARGO_BUILD_RUSTFLAGS = "-C target-feature=+crt-static -C codegen-units=1";
          CC_aarch64_unknown_linux_musl = "${clang}/bin/clang";
          CXX_aarch64_unknown_linux_musl = "${clang}/bin/clang++";
          nativeBuildInputs = with pkgs; [ protobuf llvmPackages.clang pkg-config git ];
          LIBCLANG_PATH = "${pkgs.llvmPackages.libclang.lib}/lib";
          PROTOC = "${pkgs.protobuf}/bin/protoc";
        };
      });
}
