# This is a boring build workflow that just builds the project on
# mac, ubuntu and windows. Just to check that the optional compiler
# flags that don't work on a developer's computer still build on 
# other OS. 
name: Boring Build

on:
  push:
    branches:
      - main
    paths:
      - '**.rs'
      - '**.toml'
  pull_request:
    branches:
      - main
    paths:
      - '**.rs'
      - '**.toml'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Use rust-toolchain.toml
        run: rustup show

      - name: Cache Cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Build project
        run: cargo build
